env:
  TERM: xterm-256color

dpi:
  x: 96.0
  y: 96.0

tabspaces: 4
draw_bold_text_with_bright_colors: true
render_timer: false

font:
  AppleFontSmoothing: true

  # normal:
  #   family: Anonymice Nerd Font Mono

  # normal:
  #   family: ImWritingMonoS Nerd Font Mono

  # normal:
  #   family: iMWritingMonoS Nerd Font

  # normal:
  #   family: iMWritingMonoS NF

  # normal:
  #   family: FiraCode NFM
  #   style: Retina
  # bold:
  #   family: FiraCode NFM
  # italic:
  #   family: FiraCode NFM

  # normal:
  #   family: CaskaydiaCove Nerd Font Mono

  normal:
    # family: Go Mono Nerd Font
    # family: DaddyTimeMono Nerd Font
    # family: DejavuSansMono Nerd Font
    family: JetBrainsMono NFM

  size: 9.5

colors:
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'
  normal:
    black:   '0x3c3836'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xebdbb2'
  bright:
    black:   '0x7c6f64'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xb3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

visual_bell:
  duration: 0

live_config_reload: true
