import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]

normal.family = "ComicShannsMono Nerd Font Propo"
bold.family = "ComicShannsMono Nerd Font Propo"
italic.family = "ComicShannsMono Nerd Font Propo"
bold_italic.family = "ComicShannsMono Nerd Font Propo"

size = 12
