export PATH=$HOME/bin/:$HOME/.cargo/bin/:$HOME/.local/bin/:$HOME/.local/share/nvim/mason/bin/:$HOME/go/bin/:$PATH
export ZSH="$HOME/.oh-my-zsh"

export VIRTUAL_ENV_DISABLE_PROMPT=1
export DOCKER_BUILDKIT=0

ZSH_THEME="ritz"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source $HOME/python312/bin/activate
source /usr/share/doc/pkgfile/command-not-found.zsh

alias so="source $HOME/.zshrc"
