export PATH=$HOME/bin/:$HOME/.cargo/bin/:$HOME/.local/bin/:$HOME/.local/share/nvim/mason/bin/:$HOME/go/bin/:$PATH
export ZSH="$HOME/.oh-my-zsh"

export VIRTUAL_ENV_DISABLE_PROMPT=1

ZSH_THEME="ritz"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source $HOME/python312/bin/activate

alias so="source $HOME/.zshrc"
